version: "3.7"
include:
  - "./cheshire/core/docker-compose.yml"
services:
  db:
    image: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
  discordbot:
    build:
      context: "./dsbot/"
      dockerfile: Dockerfile
    depends_on:
      - db
      - cheshire-cat-core
      - cheshire-cat-vector-memory
    env_file:
      - .env
