version: "3.7"
include:
  - "./cheshire/core/docker-compose.yml"
services:
  db: 
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
  discordbot:
    build:
      context: "./dsbot/"
      dockerfile: Dockerfile
    env_file:
      - .env
